---
sudo: required

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    DOCKER_INIT: /lib/systemd/systemd

before_install:
  - |
    set -e
    docker run -d -v "${PWD}":/tmp/clickhouse --name="${DISTRIBUTION}-${DISTRIBUTION_VERSION}" --privileged ${DISTRIBUTION}:${DISTRIBUTION_VERSION} ${DOCKER_INIT}
    sleep 3
    docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt-get -qq update && apt-get -qq install apt-utils -y"
install:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt-get -qq install sudo python-pip git -y > /dev/null && pip install --upgrade pip setuptools -q && pip install ansible==${ANSIBLE_VERSION} -q"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible --version"

script:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-playbook -i /tmp/clickhouse/tests/inventory /tmp/clickhouse/tests/test.yml --syntax-check"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-playbook -i /tmp/clickhouse/tests/inventory /tmp/clickhouse/tests/test.yml -Dvv"

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/