- hosts: clickhouse-servers
  gather_facts: yes
  pre_tasks:
    - block:
        - name: Check whether SSE 4.2 instruction is set
          command: grep -q sse4_2 /proc/cpuinfo
          register: SSE4_2_support
          changed_when: False

        - name: Check whether current system supports ClickHouse
          fail:
            msg: "ClickHouse is not a cross-platform system. It requires Linux Ubuntu Precise (12.04) or newer, x86_64 architecture with SSE 4.2 instruction set."
          when: (SSE4_2_support.rc != 0) or (ansible_architecture != "x86_64") or (ansible_distribution != "Ubuntu")
      tags: [clickhouse, clickhouse-install]

  roles:
    - clickhouse
