---
# file: clickhouse/tasks/configuration.yml

- name: Manage ClickHouse configuration
  template: 
    src: config.xml.j2
    dest: "{{ clickhouse_server_config_path }}/config.xml"
    owner: "{{ clickhouse_system_user }}"
    group: "{{ clickhouse_system_group }}"
    mode: 0644
  notify:
    - Restart ClickHouse
