---
# file: clickhouse/tasks/databases.yml

- name: Manage ClickHouse databases
  uri:
    url: "http://{{ clickhouse_host |default('localhost') }}:{{ clickhouse_port |default(8123) }}/"
    method: POST
    body: "CREATE DATABASE IF NOT EXISTS {{ item }}"
    user: "{{ clickhouse_user |default('default') }}"
    password: "{{ clickhouse_password |default('') }}"
    force_basic_auth: yes
    creates: "{{ clickhouse_data_dir }}/data/{{ item }}"
  when: clickhouse_databases|length > 0
  with_items:
    - "{{ clickhouse_databases }}"
