---
# file: clickhouse/tasks/installation.yml

- name: Make sure the CA certificates are available
  apt:
    name: ca-certificates

- name: Add ClickHouse repository key
  apt_key:
    id: "{{ clickhouse_apt_key_id }}"
    url: "{{ clickhouse_apt_key_url }}"

- name: Add ClickHouse repository
  apt_repository:
    repo: "{{ clickhouse_apt_repository }}"
  register: clickhouse_apt_repository_set

- name: Update apt cache
  apt:
    update_cache: yes
  when:
    - clickhouse_apt_repository_set.changed

- name: get package facts
  package_facts:
    manager: auto

- name: Install ClickHouse packages
  apt:
    name: "{{ item.pkg }}{% if item.state == 'present' and clickhouse_version is defined and clickhouse_version != '' %}={{ clickhouse_version }}*{% endif %}"
    state: "{{ item.state }}"
    force: "{{ clickhouse_apt_force_apply }}"
    dpkg_options: "{{ dpkg_force_overwrite_configs | ternary('force-confdef,force-confnew', 'force-confdef,force-confold') }}"
    force_apt_get: yes
    update_cache: yes
    purge: yes
    cache_valid_time: "{{ clickhouse_apt_cache_timeout }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
    RUNLEVEL: 1
  with_items:
    - "{{ clickhouse_apt_packages }}"

- name: Hold {{ item.pkg }} package version
  become: yes
  dpkg_selections:
    name: "{{ item.pkg }}"
    selection: "hold"
  with_items:
    - "{{ clickhouse_apt_packages }}"
  when:
    - clickhouse_apt_hold_packages | bool
    - item.pkg in ansible_facts.packages
    - item.state != 'absent'

- name: Override clickhouse-server systemd service
  block:
    - name: Check override path
      file:
        path: /etc/systemd/system/clickhouse-server.service.d
        owner: root
        group: root
        mode: 0755
        state: directory
    - name: Create systemd service override file
      template:
        src: clickhouse-server.service.override.j2
        dest: /etc/systemd/system/clickhouse-server.service.d/override.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - systemd daemon reload
        - Restart ClickHouse
  when:
    - ansible_service_mgr == 'systemd'
