---
# file: clickhouse/tasks/installation.yml

- name: Make sure the CA certificates are available
  apt:
    pkg: ca-certificates

- name: Add ClickHouse repository apt-key
  apt_key:
    id: "{{ clickhouse_apt_key_id }}"
    url: "{{ clickhouse_apt_key_url }}"

- name: Add ClickHouse repository
  apt_repository:
    repo: "{{ clickhouse_apt_repository }}"

- name: Install ClickHouse packages
  apt:
    name: "{{ item.pkg }}"
    state: "{{ item.state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - "{{ clickhouse_apt_packages }}"
