---
# file: clickhouse/tasks/main.yml

- import_tasks: installation.yml
  tags: [clickhouse, clickhouse-install]

- name: Ensure ClickHouse is running
  service:
    name: clickhouse-server
    state: started
  tags:
    - clickhouse
    - clickhouse-install
    - clickhouse-databases

- import_tasks: configuration.yml
  tags: [clickhouse, clickhouse-configure]

- import_tasks: users.yml
  tags: [clickhouse, clickhouse-users]

- import_tasks: databases.yml
  tags: [clickhouse, clickhouse-databases]
