---
# file: clickhouse/handlers/main.yml

- name: Start ClickHouse
  service:
    name: clickhouse-server
    state: running
    enabled: yes
    pattern: /usr/bin/clickhouse-server

- name: Restart ClickHouse
  service:
    name: clickhouse-server
    state: restarted
